### ISSUE TITLE
drivetemp and HD spin down

### ISSUE THREAD

**Issue by retep-koylus** [groeck/drivetemp#2]
Hi,

I'm a happy user of this new driver. Thanks for that.
Based on the HD temperature values coming from sysfs I created a simple script to control fans.

I would have a question related to this. If I use my script and the read HD temperature values regularly then
HDs will not spin down at all. Can you imagine that drivetemp module can operate in such a way when advanced power managment settings of the HDs are respected? Or it is not possible at all?
Let me know your view on this.
Thanks,

Peter

**Comment by groeck** [comment]
Sorry, I don't know if there is a means to read the drive temperature without affecting spin down. If someone knows how to do this, I'll be happy to implement it.

**Comment by retep-koylus** [comment]
Thanks for the reply. I do not have a clue either.
I assume if there is a solution for this then `smartmontools` team will know about that.
I try to do some investigation and come back if I found something.

**Comment by retep-koylus** [comment]
Hi Günter,

I have some good news. The situation seems to be better than I thought.

I use 8 x 12TB WD Red NAS (WD120EFAX) drives in a ZFS pool on Debian 10.5 (back-ported kernel 5.6).
The spin down time for my HDs is 20 min configured with `hdparm`.

My observation is that following:
- If the HDs' temperature is read in every 40 minutes or greater time period (i.e. minimum 2 times of the spin down time) using `drivetemp` module then the HDs can spin down properly
- If the HDs are in standby mode then additional `drivetemp` activity will not wake them up
- And even bigger surprise is that 'drivetemp' is fully functional in HD's standby mode, it can report the temperature properly (while `hddtemp` and `smartmontools` cannot do the same)

My conclusions are:
- `drivetemp` behaves similarly to `hddtemp` and `smartd`. If any of them communicates with HDs in spin down time period then they do not let the HDs go standby mode.
- If the HDs are in standby mode then 'drivetemp' is still functional (this is a big advantage!)
- If the HD's power management is important then consider to align read frequency and spin down time in the following way:
       read frequency >= 2 * spin down time
- If a near real-time monitoring of the HD temperature is a must (e.g. in a server environment) then forget about HD power saving

So I do not see any need to change the current implementation of `drivetemp` (despite of the fact that I can track the change of HD temperature in every 40 minutes only). 
Let me know your view on this and feel free to correct any of my mistakes here.
Thanks for your good job again!

Peter

**Comment by groeck** [comment]
@retep-koylus : Thanks a lot for the information. I'll add it to the upstream driver as usage note. Do you have a name/e-mail address I can use to credit you. or do you prefer to stay anonymous ? Feel free to send a note directly to linux@roeck-us.net.
